### ISSUE TITLE
Git-based version of utt

### ISSUE THREAD

**Issue by beevabeeva** [larose/utt#18]
Hi,

I'm working on a feature that allows one to log hours on multiple machines.
It requires the user to create a repo on github or gitlab where the most up to date version of
the utt.log file is stored.

Check out my [fork](https://github.com/beevabeeva/utt) of utt for more info.

This is a work in progress and far from being ready for a pull request.
Just though I'd let you know.

Cheers

**Comment by larose** [comment]
Thank you for taking the time to improve utt @beevabeeva.

Unfortunately, I think utt should be independent of the underlying synchronization/backup strategy for the timesheet. So I'd prefer to not add git to utt.

With that being said, if you create a tool that combines utt with git, I'll be more than happy to add a link to your tool.

**Comment by beevabeeva** [comment]
Wow thanks! What a great opportunity. Makes sense to have it as a separate tool.
Will work on it in my spare time and make some docs too.

All the best

:+1:

**Comment by larose** [comment]
Hi @beevabeeva, I just wanted to let you know that I added support for plugins: https://github.com/larose/utt/blob/master/docs/PLUGINS.md . The API is not stable yet, but it's a first step.
