### ISSUE TITLE
OSError: [Errno 22] Invalid argument (When deleting content of report-file)

### ISSUE THREAD

**Issue by kentaasvang** [larose/utt#19]
When trying to run **utt hello** after manually deleting all the content in the report-file. I did this to start over.

The error comes from **add_entry.py** on line 26. If the report-file is empty you can't put the cursor on position -1

```python
with open(filename, "rb+") as file:
    file.seek(-1, os.SEEK_END)  # if the file is empty, position -1 will cause OSError
   ...
```

I fixed it by catching the exception and ignoring the issue, whilst setting;
```python
prepend_new_line = False
```
I'm creating a pull request for it. Just in case

**Comment by larose** [comment]
Fixed in #61.
