### ISSUE TITLE
Report for "one month"

### ISSUE THREAD

**Issue by ukrutt** [larose/utt#22]
It would be convenient to be able to report for "a month" at a time.  

Of course, this is already possible to do (`--from 2019-10-01 --to 2019-10-31` for October) but it would be convenient to be able to do just `utt report --month 2019-10` or `utt report --month Oct`.  

It would be pretty easy to implement the `--month` command line switch.  However it would be even more user friendly if we could write `utt report Oct`.  

Is there any interest in this?  Which is the better approach?  `--month` switch or automatic parsing?

(In either case I volunteer to do the work!)

UPDATE: Solved in #25.

**Comment by larose** [comment]
Fixed in #25
