### ISSUE TITLE
Weekly and monthly date reports

### ISSUE THREAD

**Issue by bchhun** [larose/utt#4]
The daily report is useful but I need a **weekly** and/or a **monthly** report as well sometimes.

Here's a draft of how it would work with the *report* argument:
    
    # 1. would give us a report from 2014-01-01 to 2014-01-15
    $ utt report --start-date=2014-01-01 --end-date=2014-01-15 
    # 2. the original report command without the --start-date and 
    #    --end-date argument would have the same behavior as of now.
    $ utt report
    # 3. the "weekly" string would fetch the current week's start and end dates and 
    #    use the first example under the hood.
    $ utt report weekly
    # 4. the "monthly" string would work the same way as the "weekly" one but 
    #    with the correct start & end dates.
    $ utt report monthly
    # 5. The same goes for "yearly"
    $ utt report yearly

I'll work on this when I'll have some spare time.

How does it look to you ?

**Comment by larose** [comment]
That's perfect! I look forward to your pull request!
