### ISSUE TITLE
Say "bye"

### ISSUE THREAD

**Issue by 1kastner** [larose/utt#5]
Just an idea to leave: In the morning I say "hello", why not say "bye" in the evening? I am new to the software and I do not want it to record my sleeping time as work time, so I thought about that. Or do you have another idea and already solved this?

**Comment by larose** [comment]
See #1 :)

**Comment by larose** [comment]
1kastner wrote:
> So how does this behave when I am a night coder? Will it just look at my last activity which I started at 23:59 and believe it was the last entry of the day? That would be a bit problematic for me because I could reach that border. Or is this what "hello" is good for? Is it meant in the way that between an activity and a hello the time is ignored? So I could also use hello during the day instead of breaks in case I want so?

> I love this project and thanks for your effort and sharing :+1: 

Let's say an activity is from 23:00 to 1:00. In which report do you expect to see it?

**Comment by 1kastner** [comment]
I would not care about for which day it is written down because I am doing this only for myself. It should be for either of the two days or it could also be split at midnight and appear in both. Whatever is convenient.

**Comment by larose** [comment]
I think the best option for you now is to "add" at 23:59 and "hello" at 00:00.

If you have an idea and would like to implement it, I accept pull request. Send me an email before starting.

**Comment by 1kastner** [comment]
could I do so now?

**Comment by larose** [comment]
Send me an email at mathieu@mathieularose.com
