### ISSUE TITLE
Problem when using incorrect python version

### ISSUE THREAD

**Issue by robert-franz** [larose/utt#71]
On my operating system debian 9 there is python 3.5.3 installed by default. When now running utt 1.21 I get the following exception:
```
> utt hello
Traceback (most recent call last):
  File "/home/user/.local/bin/utt", line 7, in <module>
    from utt.__main__ import main
  File "/home/user/.local/lib/python3.5/site-packages/utt/__main__.py", line 34
    commands: Commands = _v1._private.container[Commands]
            ^
SyntaxError: invalid syntax
```
When having a look to the `Pipfile` I can see that python 3.7 is required. https://github.com/larose/utt/blob/master/Pipfile

It would be great to have some kind of proper exception message in case a not supported version is used.

**Comment by larose** [comment]
Hi @robert-franz, thanks for your feedback. I've just released version 1.22 that prints a warning if the python version is not supported. I also added the python version requirement to the readme.

**Comment by robert-franz** [comment]
The warning works for me :) Thx. for the fast response.

**Comment by larose** [comment]
Thanks :)
