### ISSUE TITLE
Export working times in excel sheet

### ISSUE THREAD

**Issue by Tylopilus** [larose/utt#80]
I am interested in exporting my working times as an excel-sheet, or even better just as a csv. Does utt offer this ootb? Otherwise it would be great if such functionality would be added.

This would make it way easier to import the times in other tools like asana or jira. Any chance this is planned in the near future?

**Comment by ukrutt** [comment]
The `report` verb has a `--csv-section` switch -- does it do what you need?  
```
utt report --help
```

**Comment by larose** [comment]
Thanks @ukrutt for the quick response. I'll close this issue, but @Tylopilus let us know if this isn't what were looking for.
