### ISSUE TITLE
Why doesn't the Activity Report account for time spent in tasks started in the previous day?

### ISSUE THREAD

**Issue by resolritter** [larose/utt#89]
I am phrasing this as a question instead of an issue because I don't know it this is intended

Suppose you have a log like the following

```
2020-12-29 23:00 Task A

2020-12-30 00:20 Task B
```

When I get the report with `utt report`, in the `ActivitiesView` report, Task B will account for 20 minutes instead of 80 minutes. It seems to be counting from midnight instead of when the task actually started - in the previous day, before midnight; this feels incorrect IMO.

**Comment by larose** [comment]
Indeed, that seems odd. I'll have a look at it.

**Comment by larose** [comment]
The report command filters activities between a start and end time. Running `utt report` without specifying a filter uses the default one which is today from midnight to midnight. Therefore, when asking for a report from midnight to midnight, only 20 minutes was spent on "Task B" within the requested range. Part of "Task B" was truncated to only keep what fits in the requested range. If you run `utt report --from yesterday`, utt would return 80 minutes for "Task B".

I think what you are looking for is an option that would not truncate activities. You could probably implement this feature in a plugin, although I think it would require a few changes in the plugin system and utt core components.

**Comment by resolritter** [comment]
Thanks for the explanation. It does make sense.

I was thinking the following behavior would make sense by default

```
IF filtering starting from today, look at today's history
   IF today has a "hello" entry, it means that the task could not be started on a previous day
        STOP
   ELSE
      Look back into the past into the history until a day has a "hello" entry
      Get the last task's stop time
      Stretch the current task from there until today
```

However, that would be at odds with the current behavior of "Consider `hello` to be at midnight if there's no `hello` for the current day". That being the case, I suppose this can't be solved.
